services:
  backend:
    build: ./backend
    ports:
      - "4000:3000"
    env_file:
      - backend/.env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - frontend/.env

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - unicloud_data:/var/lib/postgresql/data

volumes:
  unicloud_data:
